### ISSUE TITLE
skip box won't start on OS X el capitan

### ISSUE THREAD

**Issue by serverchief** [skippbox/skippbox#13]
BlueFin-MacBook-Pro:skippbox imusayev$ npm start

> skippbox@0.0.1 start /Users/imusayev/skippbox
> nw

[3773:0126/114133:WARNING:dns_config_service_posix.cc(151)] dns_config has unhandled options!
[3773:0126/114133:INFO:CONSOLE(103)] "", source: file:///Users/imusayev/skippbox/js/controllers/services.js (103)
[3773:0126/114133:INFO:CONSOLE(107)] ""Error: [$injector:undef] http://errors.angularjs.org/1.4.5/$injector/undef?p0=config\n    at Error (native)\n    at file:///Users/imusayev/skippbox/js/lib/angular.min.js:6:416\n    at Object.$get (file:///Users/imusayev/skippbox/js/lib/angular.min.js:37:32)\n    at Object.e [as invoke] (file:///Users/imusayev/skippbox/js/lib/angular.min.js:39:96)\n    at file:///Users/imusayev/skippbox/js/lib/angular.min.js:40:410\n    at d (file:///Users/imusayev/skippbox/js/lib/angular.min.js:38:308)\n    at Object.e [as invoke] (file:///Users/imusayev/skippbox/js/lib/angular.min.js:39:64)\n    at Q.instance (file:///Users/imusayev/skippbox/js/lib/angular.min.js:80:151)\n    at L (file:///Users/imusayev/skippbox/js/lib/angular.min.js:61:140)\n    at g (file:///Users/imusayev/skippbox/js/lib/angular.min.js:54:326)"", source: file:///Users/imusayev/skippbox/js/lib/angular.min.js (107)

**Comment by runseb** [comment]
thanks for reporting the issue @serverchief looking into it.

**Comment by runseb** [comment]
Can you try to hit CMD + R

**Comment by raynjamin** [comment]
@runseb @serverchief Check your version of Chrome? Found some hits on nwjs forums as well as the atom repo on this error, it seems like there's been a patch in Chrome to fix it. 

In Atom's case it was not a fatal error, doesn't seem like it should be for nwjs either.

**Comment by olivierlemasle** [comment]
Hi @runseb @serverchief 

This issue occurs when you have no ~/kube/config file.
The fatal error was due to the fact that an Angular factory always expect a return object.
Additionally, the error message was not printed in the logs.
